-- connect masterqoala

---
prompt Criando role RL_QOALA para novos usuários do sistema
drop role RL_QOALA;
create role RL_QOALA;

GRANT CONNECT TO RL_QOALA;
GRANT CREATE SESSION TO RL_QOALA;
GRANT ALTER SESSION TO RL_QOALA;

--
prompt Criando usuario owner do sistema
drop user qoala cascade;
CREATE USER qoala IDENTIFIED BY "Q41L1@2016"
  DEFAULT TABLESPACE "USERS"
  TEMPORARY TABLESPACE "TEMP";

GRANT ALTER USER TO QOALA;
GRANT CREATE USER TO QOALA;
GRANT DROP USER TO QOALA;

ALTER USER "QOALA" QUOTA UNLIMITED ON USERS;

GRANT RL_QOALA to qoala with admin option;


---
prompt Criando usuario de servicos
DROP USER qoala_user;
CREATE USER qoala_user IDENTIFIED BY "Q41L1@2016"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER "QOALA_USER" QUOTA UNLIMITED ON USERS;
grant RL_QOALA to qoala_user;
