CREATE OR REPLACE VIEW VW_POSTS_USER AS
SELECT ID_POST, TITLE "TITULO", P.CREATED_AT "DATA_CRIACAO", P.PUBLISHED_AT "DATA_PUBLICAO", NAME "AUTOR", EMAIL "EMAIL_AUTOR",
       CASE PERMISSION
             WHEN 3 THEN 'Administrador'
             WHEN 2 THEN 'Editor'
             ELSE 'Público' END "PERFIL"
       FROM POSTS P
       INNER JOIN USERS U ON P.ID_USER = U.ID_USER;
