CREATE OR REPLACE VIEW VW_POST_COMMENTS AS
SELECT VW_P.ID_POST "ID_NOTICIA", VW_P.TITULO "TITULO_NOTICIA", VW_P.AUTOR "AUTOR_NOTICIA",
              ID_COMMENT "ID_COMENTARIO", C.CONTENT "COMENTARIO", C.CREATED_AT "DATA_COMENTARIO", C.APPROVED_AT "DATA_APROVACAO", U.NAME "AUTOR_COMENTARIO"
       FROM VW_POSTS_USER VW_P
       LEFT JOIN COMMENTS C ON VW_P.ID_POST = C.ID_POST
       INNER JOIN USERS U ON C.ID_USER = U.ID_USER;
