CREATE OR REPLACE VIEW VW_USER_DEVICES AS
SELECT NAME, EMAIL, ADDRESS, DISTRICT, CITY, STATE, ZIPCODE, ALIAS, FREQUENCY_UPDATE
       FROM USERS U
       LEFT JOIN DEVICES D ON U.ID_USER = D.ID_USER;
