-- muda o schema, pois será executado como masterqoala
-- todas as tabelas deverão ser criadas com owner QOALA
alter session set current_schema=qoala;

DROP
  TABLE COMMENTS CASCADE CONSTRAINTS ;

DROP
  TABLE COMMENT_LOGS CASCADE CONSTRAINTS ;

DROP
  TABLE DEVICES CASCADE CONSTRAINTS ;

DROP
  TABLE DEVICE_GEO_LOCATIONS CASCADE CONSTRAINTS ;

DROP
  TABLE DEVICE_GEO_LOCATION_LOGS CASCADE CONSTRAINTS ;

DROP
  TABLE DEVICE_LOGS CASCADE CONSTRAINTS ;

DROP
  TABLE INFO_COMPANY CASCADE CONSTRAINTS ;

DROP
  TABLE POSTS CASCADE CONSTRAINTS ;

DROP
  TABLE POST_LOGS CASCADE CONSTRAINTS ;

DROP
  TABLE USERS CASCADE CONSTRAINTS ;

DROP
  TABLE USER_LOGS CASCADE CONSTRAINTS ;

CREATE
  TABLE COMMENTS
  (
    ID_COMMENT INTEGER NOT NULL ,
    CONTENT CLOB NOT NULL ,
    CREATED_AT  DATE NOT NULL ,
    UPDATED_AT  DATE ,
    APPROVED_AT DATE ,
    DELETED_AT  DATE ,
    POST_ID     INTEGER NOT NULL ,
    USER_ID     INTEGER NOT NULL
  ) ;
ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_PK PRIMARY KEY ( ID_COMMENT ) ;


CREATE
  TABLE COMMENT_LOGS
  (
    LOG CLOB NOT NULL ,
    COMMENTS_ID INTEGER NOT NULL ,
    CREATED_AT  DATE NOT NULL
  ) ;


CREATE
  TABLE DEVICES
  (
    ID_DEVICE        INTEGER NOT NULL ,
    ALIAS            VARCHAR2 (50) NOT NULL ,
    COLOR            VARCHAR2 (15) ,
    FREQUENCY_UPDATE INTEGER NOT NULL ,
    LAST_LONGITUDE FLOAT (9) ,
    LAST_LATITUDE FLOAT (9) ,
    ALARM      CHAR (1) ,
    USER_ID    INTEGER NOT NULL ,
    CREATED_AT DATE NOT NULL ,
    UPDATED_AT DATE ,
    DELETED_AT DATE
  ) ;
ALTER TABLE DEVICES ADD CONSTRAINT DEVICE_PK PRIMARY KEY ( ID_DEVICE ) ;


CREATE
  TABLE DEVICE_GEO_LOCATIONS
  (
    ID_DEVICE_GEO_LOCATION INTEGER NOT NULL ,
    DEVICE_ID              INTEGER NOT NULL ,
    VERIFIED_AT            DATE NOT NULL ,
    LATITUDE FLOAT (9) NOT NULL ,
    LONGITUDE FLOAT (9) NOT NULL
  ) ;
ALTER TABLE DEVICE_GEO_LOCATIONS ADD CONSTRAINT DEVICE_GEO_LOCATION_PK PRIMARY
KEY ( ID_DEVICE_GEO_LOCATION ) ;


CREATE
  TABLE DEVICE_GEO_LOCATION_LOGS
  (
    LOG CLOB NOT NULL ,
    DEVICE_GEO_LOCATION_ID INTEGER NOT NULL ,
    CREATED_AT             DATE NOT NULL
  ) ;


CREATE
  TABLE DEVICE_LOGS
  (
    LOG CLOB NOT NULL ,
    DEVICE_ID  INTEGER NOT NULL ,
    CREATED_AT DATE NOT NULL
  ) ;


CREATE
  TABLE INFO_COMPANY
  (
    KEY VARCHAR2 (20) ,
    VALUE CLOB
  ) ;


CREATE
  TABLE POSTS
  (
    ID_POST INTEGER NOT NULL ,
    TITLE   VARCHAR2 (255 BYTE) NOT NULL ,
    CONTENT CLOB NOT NULL ,
    CREATED_AT   DATE NOT NULL ,
    UPDATED_AT   DATE ,
    PUBLISHED_AT DATE ,
    DELETED_AT   DATE ,
    USER_ID      INTEGER NOT NULL
  ) ;
ALTER TABLE POSTS ADD CONSTRAINT POST_PK PRIMARY KEY ( ID_POST ) ;


CREATE
  TABLE POST_LOGS
  (
    LOG CLOB NOT NULL ,
    POST_ID    INTEGER NOT NULL ,
    CREATED_AT DATE NOT NULL
  ) ;


CREATE
  TABLE USERS
  (
    ID_USER    INTEGER NOT NULL ,
    NAME       VARCHAR2 (255) NOT NULL ,
    PASSWORD   VARCHAR2 (255) NOT NULL ,
    EMAIL      VARCHAR2 (255) NOT NULL ,
    PERMISSION INTEGER DEFAULT 1 NOT NULL ,
    CREATED_AT DATE NOT NULL ,
    UPDATED_AT DATE
  ) ;
ALTER TABLE USERS ADD CONSTRAINT CK_USER_PERMISSION CHECK ( PERMISSION IN (1, 2
, 3)) ;
ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY ( ID_USER ) ;


CREATE
  TABLE USER_LOGS
  (
    LOG CLOB NOT NULL ,
    USER_ID    INTEGER NOT NULL ,
    CREATED_AT DATE NOT NULL
  ) ;


ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_POST_FK FOREIGN KEY ( POST_ID )
REFERENCES POSTS ( ID_POST ) ;

ALTER TABLE COMMENTS ADD CONSTRAINT COMMENTS_USER_FK FOREIGN KEY ( USER_ID )
REFERENCES USERS ( ID_USER ) ;

ALTER TABLE COMMENT_LOGS ADD CONSTRAINT COMMENT_LOG_COMMENTS_FK FOREIGN KEY (
COMMENTS_ID ) REFERENCES COMMENTS ( ID_COMMENT ) ;

ALTER TABLE DEVICE_GEO_LOCATION_LOGS ADD CONSTRAINT DEVICES_GEO_LOCATION_FK
FOREIGN KEY ( DEVICE_GEO_LOCATION_ID ) REFERENCES DEVICE_GEO_LOCATIONS (
ID_DEVICE_GEO_LOCATION ) ;

ALTER TABLE DEVICES ADD CONSTRAINT DEVICES_USER_FK FOREIGN KEY ( USER_ID )
REFERENCES USERS ( ID_USER ) ;

ALTER TABLE DEVICE_GEO_LOCATIONS ADD CONSTRAINT DEVICE_GEO_LOCATION_DEVICE_FK
FOREIGN KEY ( DEVICE_ID ) REFERENCES DEVICES ( ID_DEVICE ) ;

ALTER TABLE DEVICE_LOGS ADD CONSTRAINT DEVICE_LOG_DEVICE_FK FOREIGN KEY (
DEVICE_ID ) REFERENCES DEVICES ( ID_DEVICE ) ;

ALTER TABLE POST_LOGS ADD CONSTRAINT POST_LOG_POST_FK FOREIGN KEY ( POST_ID )
REFERENCES POSTS ( ID_POST ) ;

ALTER TABLE POSTS ADD CONSTRAINT POST_USER_FK FOREIGN KEY ( USER_ID )
REFERENCES USERS ( ID_USER ) ;

ALTER TABLE USER_LOGS ADD CONSTRAINT USER_LOG_USER_FK FOREIGN KEY ( USER_ID )
REFERENCES USERS ( ID_USER ) ;