-- EXIBE A QUANTIDADE DE DISPOSITIVOS POR CLIENTE CADASTRADO QUANDO A QUANTIDADE FOR MAIOR QUE ZERO 
SELECT NAME "CLIENTE", COUNT(ALIAS) "QTADE DE DEVICES" FROM VW_USER_DEVICES
GROUP BY NAME
HAVING COUNT(ALIAS) > 0

-- EXIBE DADOS CADASTRAIS DE USUÁRIO QUE SE CADASTRARAM PARA ACOMPANHAR O PROJETO, MAS AINDA NÃO COMPRARAM O DISPOSITIVO DE LOCALIZAÇÃO DE PETS
-- ESTE RELATÓRIO SERVE PARA QUE O TIME DE MARKETING POSSA CRIAR AÇÕES PARA CONVERCER ESSES PROSPCTES A COMPREREM O PRODUTO
SELECT "CLIENTE", EMAIL "E-MAIL DO CLIENTE", ADDRESS "ENDEREÇO", DISTRICT "BAIRRO", CITY "CIDADE", STATE "ESTADO", ZIPCODE "CEP"
FROM (SELECT NAME "CLIENTE", EMAIL, ADDRESS, DISTRICT, CITY, STATE, ZIPCODE, COUNT(ALIAS) "QTADE_DEVICES" FROM VW_USER_DEVICES
GROUP BY NAME, EMAIL,ADDRESS, DISTRICT, CITY, STATE, ZIPCODE) 
WHERE "QTADE_DEVICES" = 0

       
-- EXIBE AS NOTÍCIAS PUBLICAS POR AUTORES COM PERFIL PÚBLICO EM FASE DE DESENVOLVIMENTO 
-- E QUE DEVEM SER EXCLUÍDOS DO BANCO DE DADOS ANTES DO SISTEMA ENTRAR EM PRODUÇÃO
SELECT ID_POST, TITULO, AUTOR FROM VW_POSTS_USER
WHERE PERFIL = 'Público'


-- EXIBE SOMENTE OS COMENTÁRIOS PENDENTES DE APROVAÇÃO
SELECT ID_COMENTARIO, DATA_COMENTARIO, AUTOR_COMENTARIO, TITULO_NOTICIA, AUTOR_NOTICIA 
FROM VW_POST_COMMENTS
WHERE DATA_COMENTARIO IS NOT NULL AND DATA_APROVACAO IS NULL

-- EXIBE A QUANTIDADE DE COMENTÁRIOS NA NOTÍCIA
-- POSSIBILITA AO MARKETING MENSURAR O IMPACTO GERADO PELA PUBLICAÇÃO (QUANTO MAIS COMENTÁRIOS, MAIOR O IMPACTO GERADO)
SELECT TITULO_NOTICIA, AUTOR_NOTICIA, COUNT(ID_COMENTARIO) "QTDE_COMENTARIOS"
FROM VW_POST_COMMENTS
GROUP BY TITULO_NOTICIA, AUTOR_NOTICIA



